### ISSUE TITLE
算法补充说明

### ISSUE THREAD

**Issue by iwestlin** [njpipeorgan/LightsOut#1]
我看Readme算法说明的时候卡在这一步：

> Note that after some buttons in the second row is clicked in order to turn off the lights in the first row, configuration of lights on the second and the third row are also changed:

```
(2, 1) : a1 ^ a3 ^ 1           ( 1 0 1 0 0 | 1 )
(2, 2) : a4                    ( 0 0 0 1 0 | 0 )
(2, 3) : a1 ^ a5               ( 1 0 0 0 1 | 0 )
(2, 4) : a2                    ( 0 1 0 0 0 | 0 )
(2, 5) : a3 ^ a5 ^ 1           ( 0 0 1 0 1 | 1 )

(3, 1) : a1 ^ a2               ( 1 1 0 0 0 | 0 )
(3, 2) : a1 ^ a2 ^ a3          ( 1 1 1 0 0 | 0 )
(3, 3) : a2 ^ a3 ^ a4          ( 0 1 1 1 0 | 0 )
(3, 4) : a3 ^ a4 ^ a5          ( 0 0 1 1 1 | 0 )
(3, 5) : a4 ^ a5               ( 0 0 0 1 1 | 0 )
```

想不通为啥 (2, 1) 会和 a3 有关系。后来想了好久，用纸笔才算推出来。建议作者还是把这一个步骤写详细点，省的可能有后来者像我一样头痛……
(2, 1) 目前的状态为 a1 ^ 1
为了使 (1, 1) 的状态变为 0
(2, 1) 作为第二行唯一能影响到 (1, 1) 的，需要重复一遍 (1, 1) 已经进行的操作 (即 a1 ^ a2 ^ 1)，这是因为任何一个数异或其本身结果都为 0
所以 (2, 1) 的状态为 a1 ^ 1 ^ a1 ^ a2 ^ 1
可是第二行 (2, 2) 的操作又会影响到 (2, 1)，所以我们要把 (2, 2) 的操作也考虑进来，易知它的操作也就是 (1, 2) 的状态即 a1 ^ a2 ^ a3 ^ 1
所以 (2, 1) 的状态最终为 (a1 ^ 1 ^ a1 ^ a2 ^ 1) ^ (a1 ^ a2 ^ a3 ^ 1) = a1 ^ a3 ^ 1

**Comment by njpipeorgan** [comment]
The explanations of this part are modified.
